/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as NewRouteImport } from "./routes/new";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as NewSetupRouteImport } from "./routes/new_.setup";
import { Route as ProjectsProjectIdWriteRouteImport } from "./routes/projects.$projectId.write";

const NewRoute = NewRouteImport.update({
  id: "/new",
  path: "/new",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const NewSetupRoute = NewSetupRouteImport.update({
  id: "/new_/setup",
  path: "/new/setup",
  getParentRoute: () => rootRouteImport,
} as any);
const ProjectsProjectIdWriteRoute = ProjectsProjectIdWriteRouteImport.update({
  id: "/projects/$projectId/write",
  path: "/projects/$projectId/write",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/new": typeof NewRoute;
  "/new/setup": typeof NewSetupRoute;
  "/projects/$projectId/write": typeof ProjectsProjectIdWriteRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/new": typeof NewRoute;
  "/new/setup": typeof NewSetupRoute;
  "/projects/$projectId/write": typeof ProjectsProjectIdWriteRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/new": typeof NewRoute;
  "/new_/setup": typeof NewSetupRoute;
  "/projects/$projectId/write": typeof ProjectsProjectIdWriteRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/new" | "/new/setup" | "/projects/$projectId/write";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/new" | "/new/setup" | "/projects/$projectId/write";
  id: "__root__" | "/" | "/new" | "/new_/setup" | "/projects/$projectId/write";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  NewRoute: typeof NewRoute;
  NewSetupRoute: typeof NewSetupRoute;
  ProjectsProjectIdWriteRoute: typeof ProjectsProjectIdWriteRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/new": {
      id: "/new";
      path: "/new";
      fullPath: "/new";
      preLoaderRoute: typeof NewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/new_/setup": {
      id: "/new_/setup";
      path: "/new/setup";
      fullPath: "/new/setup";
      preLoaderRoute: typeof NewSetupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/projects/$projectId/write": {
      id: "/projects/$projectId/write";
      path: "/projects/$projectId/write";
      fullPath: "/projects/$projectId/write";
      preLoaderRoute: typeof ProjectsProjectIdWriteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  NewSetupRoute: NewSetupRoute,
  ProjectsProjectIdWriteRoute: ProjectsProjectIdWriteRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
